version: "3"

networks:
  backend:
      driver: ${NETWORKS_DRIVER}
  frontend:
      driver: ${NETWORKS_DRIVER}

services:
### NGINX Server #########################################
    nginx:
        image: 'nginx'
        container_name: 'nginx'
        args:
            - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
            - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        volumes:
          - ${NGINX_WWW_PATH}:/usr/share/nginx/html:rw
          - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
          - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
          - ${NGINX_LOG_PATH}:/var/log/nginx
          - ${NGINX_CONF_FILE_PATH}:/etc/nginx/nginx.conf
        ports:
          - "${NGINX_HOST_HTTP_PORT}:80"
          - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
          - php-fpm
        networks:
          - frontend
          - backend
        privileged: true
    php-fpm:
      build:
        context: ./php-fpm
      container_name: 'php-fpm'
      ports:
        - "${PHP_FPM_PORT}:9000"
      expose:
        - "9000"
      networks:
        - backend
      volumes:
        - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini
        - ${NGINX_WWW_PATH}:/usr/share/nginx/html:rw
        - ${PHP_FPM_LOG_PATH}:/var/log/php
        - ${PHP_FPM_CONF_PATH}:/etc/php-fpm.d
      privileged: true
    mysql:
      image: 'mysql:5.6'
      container_name: 'mysql'
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - ${MYSLQ_CONF_FILE_PATH}:/etc/mysql/my.cnf
        - ${MYSQL_DATA_PATH}:/var/lib/mysql
        - ${MYSQL_LOG_PATH}:/var/log/mysql
      ports:
        - "${MYSQL_PORT}:3306"
    redis:
      image: 'redis'
      container_name: 'redis'
      volumes:
        - ${REDIS_CONF_FILE_PATH}:/usr/local/etc/redis/redis.conf
        - ${REDIS_LOG_PATH}:/var/log/redis
      ports:
        - "${REDIS_PORT}:6379"
    mongodb:
      image: 'mongo'
      container_name: 'mongodb'
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      command: --logpath /var/log/mongodb/mongo.log
      volumes:
        - ${MONGODB_DATA_PATH}:/data/db
        - ${MONGODB_LOG_PATH}:/var/log/mongodb
      ports:
        - "${MONGODB_PORT}:27017"