version: "3"
networks:
  backend:
      driver: ${NETWORKS_DRIVER}
  frontend:
      driver: ${NETWORKS_DRIVER}
services:
### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
    container_name: 'nginx'
    restart: always
    volumes:
      - ${NGINX_WWW_PATH}:/usr/share/nginx/html
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_CONF_FILE_PATH}:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - frontend
      - backend
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
    container_name: 'php-fpm'
    restart: always
    expose:
      - "9000"
    networks:
      - backend
    volumes:
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini
      - ${NGINX_WWW_PATH}:/usr/share/nginx/html
      - ${PHP_FPM_CONF_PATH}:/etc/php-fpm.d
  mysql:
    image: 'mysql:5.7'
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_CONF_PATH}:/etc/mysql/my.cnf
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
          - backend
  redis:
    build:
      context: ./redis
    container_name: 'redis'
    restart: always
    command: /etc/redis/redis.conf --appendonly yes
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONF_PATH}:/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
  mongodb:
    image: 'mongo'
    container_name: 'mongodb'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - backend