version: "3"

networks:
  backend:
      driver: "bridge"
  frontend:
      driver: "bridge"

services:
### NGINX Server #########################################
    nginx:
        image: 'nginx'
        container_name: 'nginx'
        volumes:
          - /www:/usr/share/nginx/html:rw
          - /docker/nginx/sites:/etc/nginx/sites-available
          - /docker/nginx/conf.d:/etc/nginx/conf.d
          - /docker/nginx/log:/var/log/nginx
          - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - php-fpm
        networks:
          - frontend
          - backend
        privileged: true
    php-fpm:
      build:
        context: ./php-fpm
      container_name: 'php-fpm'
      ports:
        - "9000:9000"
      expose:
        - "9000"
      networks:
        - backend
      volumes:
        - /docker/php-fpm/php5.6.ini:/usr/local/etc/php/php.ini
        - /www:/usr/share/nginx/html:rw
      privileged: true