version: "3"

networks:
  backend:
      driver: "bridge"
  frontend:
      driver: "bridge"

services:
### NGINX Server #########################################
    nginx:
        image: 'nginx'
        container_name: 'nginx'
        volumes:
          - /www:/usr/share/nginx/html:rw
          - /docker/nginx/sites:/etc/nginx/sites-available
          - /docker/nginx/conf.d:/etc/nginx/conf.d
          - /docker/nginx/log:/var/log/nginx
          - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - php-fpm
        networks:
          - frontend
          - backend
        privileged: true
    php-fpm:
      build:
        context: ./php-fpm
      container_name: 'php-fpm'
      ports:
        - "9000:9000"
      expose:
        - "9000"
      networks:
        - backend
      volumes:
        - /docker/php-fpm/php5.6.ini:/usr/local/etc/php/php.ini
        - /www:/usr/share/nginx/html:rw
      privileged: true
    mysql:
      image: 'mysql'
      container_name: 'mysql'
      environment:
        MYSQL_ROOT_PASSWORD: 'admin'
        MYSQL_USER: 'test'
        MYSQL_PASSWORD: 'test'
      ports:
        - "3306:3306"
    redis:
      image: 'redis'
      container_name: 'redis'
      ports:
        - "6379:6379"
    mongodb:
      image: 'mongo'
      container_name: 'mongodb'
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - "27017:27017"